// Date: 14-9-2013 18:20:20
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package com.tridevmc.davincisvessels.client.render;

import javax.annotation.Nonnull;

import com.google.common.collect.ImmutableList;

import com.tridevmc.davincisvessels.common.entity.EntityParachute;

import net.minecraft.client.model.ListModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.MeshDefinition;

public class ModelParachute extends ListModel<EntityParachute> {
    //fields
    ModelPart side0;
    ModelPart side1;
    ModelPart roof;
    ModelPart side2;
    ModelPart side3;
    int textureWidth;
    int textureHeight;

    public ModelParachute() {
        textureWidth = 128;
        textureHeight = 64;

        MeshDefinition side0definition = new MeshDefinition();
        side0definition.getRoot().addOrReplaceChild("side0",
            CubeListBuilder.create()
                .texOffs(0, 0)
                .addBox(-16.0F, -16.0F, 0.0F, 32, 32, 1)
                .mirror(true),
            PartPose.offsetAndRotation(0.0F, 0.0F, 16.0F, 0F, 0F, 0F)
        );
        side0 = side0definition.getRoot().bake(textureWidth, textureHeight);

        MeshDefinition side1definition = new MeshDefinition();
        side1definition.getRoot().addOrReplaceChild("side1",
            CubeListBuilder.create()
                .texOffs(0, 0)
                .addBox(-16F, -15F, 0F, 32, 31, 1)
                .mirror(true),
            PartPose.offsetAndRotation(0.0F, 0.0F, -16.0F, 0F, 0F, 0F)
        );
        side1 = side1definition.getRoot().bake(textureWidth, textureHeight);

        MeshDefinition roofdefinition = new MeshDefinition();
        roofdefinition.getRoot().addOrReplaceChild("roof",
            CubeListBuilder.create()
                .texOffs(0, 0)
                .addBox(-16F, 0F, -16F, 32, 1, 32)
                .mirror(true),
            PartPose.offsetAndRotation(0.0F, -16.0F, 0.0F, 0F, 0F, 0F)
        );
        roof = roofdefinition.getRoot().bake(textureWidth, textureHeight);

        MeshDefinition side2definition = new MeshDefinition();
        side2definition.getRoot().addOrReplaceChild("side2",
            CubeListBuilder.create()
                .texOffs(0, 0)
                .addBox(0F, -16F, -16F, 1, 32, 33)
                .mirror(true),
            PartPose.offsetAndRotation(16.0F, 0.0F, 0.0F, 0F, 0F, 0F)
        );
        side2 = side2definition.getRoot().bake(textureWidth, textureHeight);

        MeshDefinition side3definition = new MeshDefinition();
        side3definition.getRoot().addOrReplaceChild("side3",
            CubeListBuilder.create()
                .texOffs(0, 0)
                .addBox(0F, -15F, -15F, 1, 31, 31)
                .mirror(true),
            PartPose.offsetAndRotation(-16.0F, 0.0F, 0.0F, 0F, 0F, 0F)
        );
        side3 = side3definition.getRoot().bake(textureWidth, textureHeight);
    }

    @Override
    public  void setupAnim(@Nonnull EntityParachute p_102618_, float p_102619_, float p_102620_, float p_102621_, float p_102622_, float p_102623_) {
    }

    @Override
    public Iterable<ModelPart> parts() {
        return ImmutableList.of(side0, side1, roof, side2, side3);
    }
}
